export const catsData = [
  {
    emotionTags: ["moody"],
    isGif: false,
    image: "angry.jpeg",
    alt: "A cat looking moody",
    hasDog: false,
  },
  {
    emotionTags: ["moody", "insomniac"],
    isGif: false,
    image: "angry2.jpeg",
    alt: "A cat looking moody",
    hasDog: false,
  },
  {
    emotionTags: ["moody"],
    isGif: false,
    image: "angry3.jpeg",
    alt: "A cat looking moody",
    hasDog: false,
  },
  {
    emotionTags: ["confused", "sad"],
    isGif: false,
    image: "confused.jpeg",
    alt: "A cat looking confused",
    hasDog: false,
  },
  {
    emotionTags: ["dominant", "moody"],
    isGif: false,
    image: "dominant.jpeg",
    alt: "A cat looking dominant",
    hasDog: false,
  },
  {
    emotionTags: ["happy", "relaxed"],
    isGif: false,
    image: "happy.jpeg",
    alt: "A cat looking happy",
    hasDog: false,
  },
  {
    emotionTags: ["hungry"],
    isGif: false,
    image: "hungry.jpeg",
    alt: "A cat looking hungry",
    hasDog: false,
  },
  {
    emotionTags: ["hungry"],
    isGif: false,
    image: "hungry1.jpeg",
    alt: "A cat looking hungry",
    hasDog: false,
  },
  {
    emotionTags: ["insomniac"],
    isGif: false,
    image: "insomnia.jpeg",
    alt: "A cat looking insomniac",
    hasDog: false,
  },
  {
    emotionTags: ["insomniac"],
    isGif: false,
    image: "insomnia1.jpeg",
    alt: "A cat looking insomniac",
    hasDog: false,
  },
  {
    emotionTags: ["relaxed"],
    isGif: false,
    image: "lazy.jpeg",
    alt: "A cat looking lazy",
    hasDog: false,
  },
  {
    emotionTags: ["scared"],
    isGif: false,
    image: "nervous.jpeg",
    alt: "A cat looking nervous",
    hasDog: false,
  },
  {
    emotionTags: ["sad"],
    isGif: false,
    image: "sad.jpeg",
    alt: "A cat looking sad",
    hasDog: false,
  },
  {
    emotionTags: ["sad", "moody"],
    isGif: false,
    image: "sad1.jpeg",
    alt: "A cat looking sad",
    hasDog: false,
  },
  {
    emotionTags: ["moody"],
    isGif: true,
    image: "angry.gif",
    alt: "A cat looking moody",
    hasDog: false,
  },
  {
    emotionTags: ["moody"],
    isGif: true,
    image: "angry2.gif",
    alt: "A cat looking angry",
    hasDog: false,
  },
  {
    emotionTags: ["confused"],
    isGif: true,
    image: "confused2.gif",
    alt: "A cat looking confused",
    hasDog: false,
  },
  {
    emotionTags: ["dominant"],
    isGif: true,
    image: "dominant.gif",
    alt: "A cat looking dominant",
    hasDog: false,
  },
  {
    emotionTags: ["happy"],
    isGif: true,
    image: "happy.gif",
    alt: "A cat looking happy",
    hasDog: false,
  },
  {
    emotionTags: ["hungry", "sad", "confused"],
    isGif: true,
    image: "confused.gif",
    alt: "A cat looking hungry",
    hasDog: false,
  },
  {
    emotionTags: ["hungry"],
    isGif: true,
    image: "hungry.gif",
    alt: "A cat looking hungry",
    hasDog: false,
  },
  {
    emotionTags: ["hungry"],
    isGif: true,
    image: "hungry2.gif",
    alt: "A cat looking hungry",
    hasDog: false,
  },
  {
    emotionTags: ["insomniac", "scared"],
    isGif: true,
    image: "insomnia2.gif",
    alt: "A cat looking insomniac",
    hasDog: false,
  },
  {
    emotionTags: ["relaxed"],
    isGif: true,
    image: "lazy.gif",
    alt: "A cat looking relaxed",
    hasDog: false,
  },
  {
    emotionTags: ["relaxed"],
    isGif: true,
    image: "relaxed2.gif",
    alt: "A cat looking relaxed",
    hasDog: false,
  },
  {
    emotionTags: ["scared", "sad"],
    isGif: true,
    image: "nervous.gif",
    alt: "A cat looking nervous",
    hasDog: false,
  },
  {
    emotionTags: ["scared"],
    isGif: true,
    image: "nervous2.gif",
    alt: "A cat looking scared",
    hasDog: false,
  },
  {
    emotionTags: ["sad"],
    isGif: true,
    image: "sad.gif",
    alt: "A cat looking sad",
    hasDog: false,
  },
  {
    emotionTags: ["dominant"],
    isGif: false,
    image: "dog-dominant.jpg",
    alt: "A cat on top of a dog",
    hasDog: true,
  },
  {
    emotionTags: ["dominant"],
    isGif: true,
    image: "dog-dominant-gif.gif",
    alt: "A cat attacking a dog",
    hasDog: true,
  },
  {
    emotionTags: ["hungry"],
    isGif: false,
    image: "dog-hungry.jpg",
    alt: "A cat and a dog looking for food",
    hasDog: true,
  },
  {
    emotionTags: ["moody"],
    isGif: false,
    image: "dog-moody.jpg",
    alt: "A cat annoyed by a dog",
    hasDog: true,
  },
  {
    emotionTags: ["relaxed"],
    isGif: true,
    image: "dog-relaxed-gif.gif",
    alt: "A cat and a dog relaxing",
    hasDog: true,
  },
  {
    emotionTags: ["sad"],
    isGif: false,
    image: "dog-sad.jpg",
    alt: "A cat looking sad because of dog",
    hasDog: true,
  },
];
